In [1]:
import pandas as pd

In [ ]:
path = "/home/thore/Downloads/2022_A_S.txt"
df = pd.read_csv(path, sep=";", header=0, )

,TKNR,Zst,Land,Strklas,Strnum,Datum,Wotag,Fahrtzw,Stunde,KFZ_R1,...,Bus_R2,K_Bus_R2,LoA_R2,K_LoA_R2,Lzg_R2,K_Lzg_R2,Sat_R2,K_Sat_R2,Son_R2,K_Son_R2
0,7016,8001,8,A,5,220101,6,s,1,201,...,-1,x,-1,x,-1,x,-1,x,-1,x
1,7016,8001,8,A,5,220101,6,s,2,450,...,-1,x,-1,x,-1,x,-1,x,-1,x
2,7016,8001,8,A,5,220101,6,s,3,334,...,-1,x,-1,x,-1,x,-1,x,-1,x
3,7016,8001,8,A,5,220101,6,s,4,228,...,-1,x,-1,x,-1,x,-1,x,-1,x
4,7016,8001,8,A,5,220101,6,s,5,157,...,-1,x,-1,x,-1,x,-1,x,-1,x
5,7016,8001,8,A,5,220101,6,s,6,163,...,-1,x,-1,x,-1,x,-1,x,-1,x
6,7016,8001,8,A,5,220101,6,s,7,165,...,-1,x,-1,x,-1,x,-1,x,-1,x
7,7016,8001,8,A,5,220101,6,s,8,196,...,-1,x,-1,x,-1,x,-1,x,-1,x
8,7016,8001,8,A,5,220101,6,s,9,289,...,-1,x,-1,x,-1,x,-1,x,-1,x
9,7016,8001,8,A,5,220101,6,s,10,536,...,-1,x,-1,x,-1,x,-1,x,-1,x
10,7016,8001,8,A,5,220101,6,s,11,960,...,-1,x,-1,x,-1,x,-1,x,-1,x
11,7016,8001,8,A,5,220101,6,s,12,1716,...,-1,x,-1,x,-1,x,-1,x,-1,x
12,7016,8001,8,A,5,220101,6,s,13,2222,...,-1,x,-1,x,-1,x,-1,x,-1,x
13,7016,8001,8,A,5,220101,6,s,14,2399,...,-1,x,-1,x,-1,x,-1,x,-1,x
14,7016,8001,8,A,5,220101,6,s,15,2692,...,-1,x,-1,x,-1,x,-1,x,-1,x
15,7016,8001,8,A,5,220101,6,s,16,2640,...,-1,x,-1,x,-1,x,-1,x,-1,x
16,7016,8001,8,A,5,220101,6,s,17,2676,...,-1,x,-1,x,-1,x,-1,x,-1,x
17,7016,8001,8,A,5,220101,6,s,18,2571,...,-1,x,-1,x,-1,x,-1,x,-1,x
18,7016,8001,8,A,5,220101,6,s,19,2150,...,-1,x,-1,x,-1,x,-1,x,-1,x
19,7016,8001,8,A,5,220101,6,s,20,1563,...,-1,x,-1,x,-1,x,-1,x,-1,x

In [7]:
df.head(20)

,TKNR,Zst,Land,Strklas,Strnum,Datum,Wotag,Fahrtzw,Stunde,KFZ_R1,...,Bus_R2,K_Bus_R2,LoA_R2,K_LoA_R2,Lzg_R2,K_Lzg_R2,Sat_R2,K_Sat_R2,Son_R2,K_Son_R2
0,7016,8001,8,A,5,220101,6,s,1,201,...,-1,x,-1,x,-1,x,-1,x,-1,x
1,7016,8001,8,A,5,220101,6,s,2,450,...,-1,x,-1,x,-1,x,-1,x,-1,x
2,7016,8001,8,A,5,220101,6,s,3,334,...,-1,x,-1,x,-1,x,-1,x,-1,x
3,7016,8001,8,A,5,220101,6,s,4,228,...,-1,x,-1,x,-1,x,-1,x,-1,x
4,7016,8001,8,A,5,220101,6,s,5,157,...,-1,x,-1,x,-1,x,-1,x,-1,x
5,7016,8001,8,A,5,220101,6,s,6,163,...,-1,x,-1,x,-1,x,-1,x,-1,x
6,7016,8001,8,A,5,220101,6,s,7,165,...,-1,x,-1,x,-1,x,-1,x,-1,x
7,7016,8001,8,A,5,220101,6,s,8,196,...,-1,x,-1,x,-1,x,-1,x,-1,x
8,7016,8001,8,A,5,220101,6,s,9,289,...,-1,x,-1,x,-1,x,-1,x,-1,x
9,7016,8001,8,A,5,220101,6,s,10,536,...,-1,x,-1,x,-1,x,-1,x,-1,x
10,7016,8001,8,A,5,220101,6,s,11,960,...,-1,x,-1,x,-1,x,-1,x,-1,x
11,7016,8001,8,A,5,220101,6,s,12,1716,...,-1,x,-1,x,-1,x,-1,x,-1,x
12,7016,8001,8,A,5,220101,6,s,13,2222,...,-1,x,-1,x,-1,x,-1,x,-1,x
13,7016,8001,8,A,5,220101,6,s,14,2399,...,-1,x,-1,x,-1,x,-1,x,-1,x
14,7016,8001,8,A,5,220101,6,s,15,2692,...,-1,x,-1,x,-1,x,-1,x,-1,x
15,7016,8001,8,A,5,220101,6,s,16,2640,...,-1,x,-1,x,-1,x,-1,x,-1,x
16,7016,8001,8,A,5,220101,6,s,17,2676,...,-1,x,-1,x,-1,x,-1,x,-1,x
17,7016,8001,8,A,5,220101,6,s,18,2571,...,-1,x,-1,x,-1,x,-1,x,-1,x
18,7016,8001,8,A,5,220101,6,s,19,2150,...,-1,x,-1,x,-1,x,-1,x,-1,x
19,7016,8001,8,A,5,220101,6,s,20,1563,...,-1,x,-1,x,-1,x,-1,x,-1,x